[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
authors = ["Daniel AIdrete <aldretelearns@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = { version = "0.7.0-pre.2" }